// <auto-generated />
namespace Project_62131673.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Updatesend : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatesend));
        
        string IMigrationMetadata.Id
        {
            get { return "202403111505238_Updatesend"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
